positivelabels = {
    "packaging": [
        "packaging (negative)",
        "packaging (positive)"
    ],
    "duration": [
        "days (negative)",
        "days (positive)",
        "months (negative)",
        "months (neutral)",
        "months (positive)",
        "night",
        "overnight",
        "season",
        "weeks (negative)",
        "weeks (positive)",
        "years (negative)",
        "years (neutral)",
        "years (positive)"
    ],
    "fragrance": [
        "fragrance (negative/unneeded)",
        "fragrance (neutral/positive)",
        "fragrance free"
    ],
    "negative": [
        "as/ds/pig/disc (negative)",
        "as/ds/pig/disc (no change)",
        "average hydration/moisture",
        "big pimples (no change)",
        "blind pimples (no change)",
        "can't cover (as/ds/pig/disc)",
        "can't cover eye circles",
        "can't cover pimples/breakouts/blemishes",
        "can't cover redness",
        "can't cover scarring",
        "can't cover spots",
        "can't reduce puffiness",
        "caused (as/ds/pig/disc)",
        "caused blotchiness",
        "caused congestion",
        "caused dullness",
        "caused inflammation",
        "caused irritation",
        "caused itch",
        "caused peeling/flaking",
        "caused pimples/breakouts",
        "caused puffiness",
        "caused redness",
        "caused scarring",
        "caused sensitive skin",
        "caused skin redness",
        "cleanser (negative)",
        "damaged skin",
        "dewy (negative)",
        "discomforting",
        "dried quickly (face masks)",
        "drying (negative)",
        "eczema (negative)",
        "eczema (no change)",
        "enhanced (as/ds/pig/disc)",
        "enhanced eye circles",
        "enhanced uneven tone",
        "enhanced wrinkles",
        "enlarged pores",
        "highlighted imperfections",
        "moisturiser (negative)",
        "no difference (inflammation)",
        "no difference (pimples/breakouts)",
        "no difference (pores)",
        "no difference (redness)",
        "no difference (scarring)",
        "no difference (skin texture)",
        "no difference (skin)",
        "no difference (tanning)",
        "no difference (wrinkles)",
        "no glow",
        "no lift",
        "non-cleansing",
        "non-exfoliating",
        "non-mattifying",
        "non-plumping",
        "non-smoothing",
        "not dewy",
        "not hydrating/moisturising",
        "not nourishing",
        "not refreshing",
        "not softening",
        "not supple",
        "pores (negative)",
        "purging",
        "shiny (negative)",
        "short lasting glow",
        "showed wrinkles",
        "small pimples (no change)",
        "stings",
        "stripped (natural oils)",
        "tanning (negative)",
        "tightening (negative)",
        "worsened pimples/breakouts",
        "worsened redness"
    ],
    "positive": [
        "anti-ageing",
        "as/ds/pig/disc (positive)",
        "calming",
        "cleansing",
        "cleared pimples/breakouts",
        "cleared pores",
        "cleared skin",
        "comforting",
        "cooling/soothing",
        "covered (as/ds/pig/disc)",
        "covered pimples/breakouts/blemishes",
        "covered scarring",
        "covered wrinkles",
        "covered/reduced eye circles",
        "reduced blemishes",
        "covered/reduced redness",
        "dewy (positive)",
        "drying (pimples/breakouts)",
        "eczema (no irritation/flair ups)",
        "eczema (positive)",
        "evened tone",
        "exfoliating",
        "firming/tightening",
        "healed scarring",
        "helped big pimples",
        "helped blind pimples",
        "helped decrease tightness",
        "helped dry patches",
        "helped pimples/breakouts",
        "helped small pimples",
        "hydrating/moisturising",
        "improved complexion",
        "less blotchy",
        "less dullness",
        "less pimples/breakouts",
        "lifted skin",
        "matte finish/feel",
        "no blotch",
        "no inflammation",
        "no irritation",
        "no itch",
        "no peeling/flaking",
        "no pimples/breakouts",
        "no skin redness",
        "non-congesting",
        "non-damaging",
        "non-drying",
        "non-dulling",
        "non-quick dry (face masks)",
        "non-scarring",
        "non-shiny finish (positive)",
        "non-stinging",
        "non-stripping (natural oils)",
        "non-tightening (positive)",
        "nourishing",
        "oil control",
        "plumping",
        "pores (positive)",
        "prevented (as/ds/pig/disc)",
        "prevented pimple scarring",
        "reduced acne inflammation",
        "reduced blemishes",
        "reduced inflammation",
        "reduced irritation",
        "reduced pimples/breakouts",
        "reduced puffiness",
        "reduced wrinkles",
        "refined pores",
        "refreshing",
        "relieved itch",
        "removed residue",
        "repaired damaged skin",
        "shine/bright/glow/lumi/rad",
        "silky skin",
        "smoothed skin",
        "softened skin",
        "sun damage protection",
        "supple",
        "surfaced pimples/breakouts",
        "tanning (positive)"
    ],
    "texture": [
        "consistency (negative)",
        "consistency (neutral)",
        "consistency (positive)",
        "creamy",
        "foamy",
        "gel",
        "heavy",
        "light",
        "liquid",
        "mousse",
        "non-heavy",
        "non-sticky texture/residue",
        "oil free finish",
        "oily finish",
        "rich",
        "silky texture",
        "smooth texture",
        "soft texture",
        "sticky texture/residue",
        "thick",
        "thin"
    ]
}