# global search query parameters which should be extracted from the user's search query

# Schema for Langchain
skincare_schema = {
    "properties": {
        "skin_concern": {"type": "array", "items": {"type": "string"}},
        "skin_type": {"type": "string"},
        "skin_tone": {"type": "string"},
        "age": {"type": "integer"},
        "product_name": {"type": "string"},
        "brand": {"type": "string"},
        "product_category": {"type": "string"}, #product_category includes serums, moisturizers, toners etc
        "qualities": {"type": "string"},
        "ingredients": {"type": "array", "items": {"type": "string"}},
        "country": {"type": "string"},
        "price": {"type": "array", "items": {"type": "integer"}},
        "skincare_extra_info": {"type": "string"},
    }
}

# Define keys for search dictionary
skincare_search_query_dictionary = {
    'skin_type': '',
    'skin_tone': '',
    'age': '',
    'product_category': '',
    'skin_concern': '',
    'country': '',
    'brand': '',
    'price': '',
    'ingredients': '',
    'product_name': '',
    'qualities': ''
}

ingredients_dictionary = {
    'hyaluronic acid': ['hyaluronan', 'sodium hyaluronate', 'hyalu', 'hyaluronic'],
    'retinol': ['vitamin A', 'retinyl palmitate', 'retinaldehyde', 'tretinoin', 'adapalene', 'retin-a'],
    'vitamin C': ['ascorbic acid', 'magnesium ascorbyl phosphate', 'sodium ascorbyl phosphate', 'ascorbyl palmitate', 'vit C'],
    'niacinamide': ['vitamin B3', 'nicotinamide', 'B3'],
    'salicylic acid': ['beta hydroxy acid', 'BHA', '2-hydroxybenzoic acid', 'sal acid'],
    'glycolic acid': ['alpha hydroxy acid', 'AHA', 'glycolic'],
    'lactic acid': ['alpha hydroxy acid', 'AHA', 'milk acid', 'lactic'],
    'ceramides': ['ceramide AP', 'ceramide EOP', 'ceramide NP', 'sphingosine', 'phytosphingosine'],
    'zinc oxide': ['CI 77947', 'ZnO', 'zinc'],
    'titanium dioxide': ['CI 77891', 'TiO2', 'titanium'],
    'peptides': ['polypeptide', 'oligopeptide', 'pentapeptide', 'hexapeptide', 'peptide'],
    'jojoba oil': ['simmondsia chinensis seed oil', 'jojoba'],
    'tea tree oil': ['melaleuca alternifolia leaf oil', 'tea tree', 'melaleuca oil'],
    'rosehip oil': ['rosa canina fruit oil', 'rosa mosqueta oil', 'rosehip'],
    'argan oil': ['argania spinosa kernel oil', 'argan'],
    'avobenzone': ['butyl methoxydibenzoylmethane', 'parsol 1789', 'eusolex 9020', 'avo'],
    'octocrylene': ['2-ethylhexyl 2-cyano-3,3-diphenylacrylate', 'octocrilene', 'octo'],
    'aloe vera': ['aloe barbadensis leaf juice', 'aloe extract', 'aloe'],
    'green tea': ['camellia sinensis leaf extract', 'green tea extract', 'camellia sinensis'],
    'witch hazel': ['hamamelis virginiana water', 'hamamelis water', 'witchazel'],
    'shea butter': ['butyrospermum parkii butter', 'shea'],
    'cocoa butter': ['theobroma cacao seed butter', 'cocoa'],
    'coconut oil': ['cocos nucifera oil', 'coconut'],
    'ferulic acid': ['hydroferulic acid', '4-hydroxy-3-methoxycinnamic acid', 'ferulic'],
    'kaolin': ['china clay', 'white clay'],
    'grape seed extract': ['vitis vinifera seed extract', 'grape seed'],
    'licorice root extract': ['glycyrrhiza glabra root extract', 'licorice', 'licorice extract', 'glycyrrhiza glabra'],
    'centella asiatica': ['gotu kola', 'tiger grass', 'cica'],
    'calendula': ['calendula officinalis flower extract', 'marigold'],
    'chamomile': ['matricaria recutita flower extract', 'chamomilla recutita', 'chamo'],
    'squalane': ['squalene'],
    'benzoyl peroxide': ['BPO', 'benzoyl'],
    'collagen': ['hydrolyzed collagen', 'collagen peptides'],
    'coenzyme Q10': ['ubiquinone', 'CoQ10', 'Q10'],
    'allantoin': ['glyoxyldiureide', 'allan'],
    'panthenol': ['vitamin B5', 'pro-vitamin B5', 'pantho'],
}

extended_skincare_concerns_dictionary = {
    "acne": ["acne", "pimples", "breakouts", "blemishes", "blackheads", "whiteheads", "clogged pores", "acne-prone", "zits"],
    "aging": ["aging", "age", "wrinkles", "fine lines", "sagging", "age spots", "sundamage", "crow's feet", "crepey skin", "mature skin", "premature aging"],
    "sensitivity": ["sensitivity", "redness", "irritation", "inflammation", "rash", "allergic reaction", "sensitive skin", "reactive skin", "skin reactivity"],
    "dryness": ["dryness", "dehydration", "flaking", "peeling", "roughness", "tight skin", "dry patches", "dry skin"],
    "oiliness": ["oiliness", "sebum", "shine", "greasiness", "oily skin", "oily patches", "excess oil"],
    "pigmentation": ["pigmentation", "hyperpigmentation", "discoloration", "dark spots", "melasma", "freckles", "uneven skin color", "skin lightening", "skin darkening"],
    "scarring": ["scarring", "acne scars", "pockmarks", "post-acne marks", "stretch marks", "wound healing", "scar reduction"],
    "texture": ["texture", "roughness", "bumps", "enlarged pores", "smooth skin", "skin refinement"],
    "uneven skin tone": ["uneven skin tone", "dullness", "blotchiness", "radiance", "glow", "brightening"],
    "dark circles": ["dark circles", "puffiness", "bags under eyes", "eye bags", "eye puffiness", "tired eyes"],
    "sun protection": ["sun protection", "SPF", "sunscreen", "sunburn", "sun damage", "UV protection"],
    "eczema": ["eczema", "dermatitis", "skin rash", "skin inflammation", "atopic dermatitis"],
    "psoriasis": ["psoriasis", "scaliness", "skin patches", "plaque"],
    "rosacea": ["rosacea", "skin flushing", "visible blood vessels", "red face", "flushing", "blushing"],
    "firming": ["firming", "tightening", "lifting", "firm skin", "skin elasticity"],
    "cellulite": ["cellulite", "dimples", "lumpy skin", "orange peel skin"],
    "dull skin": ["dull skin", "lack of radiance", "lack of glow", "tired skin"],
    "keratosis pilaris": ["keratosis pilaris", "KP", "chicken skin", "rough bumps"],
    "skin protection": ["skin protection", "anti-pollution", "antioxidant protection", "blue light protection"],
    "pores": ["pores", "large pores", "visible pores", "clogged pores", "pore tightening"],
    "detox": ["detox", "purifying", "skin detox", "clearing"],
    "hormonal issues": ["hormonal imbalances", "hormonal acne", "menopausal skin", "pregnancy skin changes"],
    "environmental damage": ["environmental damage", "windburn", "pollution damage", "climate effects"],
    "dehydration": ["dehydration", "lack of moisture", "water loss", "thirsty skin"],
    "skin infections": ["skin infections", "fungal infections", "bacterial infections", "viral infections"],
    "vitiligo": ["vitiligo", "depigmentation", "white patches", "skin discoloration"],
    "sun tanning": ["sun tanning", "tanning", "sun tan", "bronzing"],
    "spider veins": ["spider veins", "varicose veins", "vascular issues", "visible veins"],
    "allergies": ["allergies", "skin allergy", "hives"],
    "dermatitis": ["dermatitis", "contact dermatitis", "atopic dermatitis", "seborrheic dermatitis"],
    "chapped lips": ["chapped lips", "dry lips", "cracked lips", "lip care"],
    "hand and nail care": ["hand care", "nail care", "cuticle health", "dry hands"],
}


skincare_labels = {
    "acne": ['effective for acne', 'acne-preventing', 'acne-prone skin friendly', 'targets bacne', 'clears blackheads', 'targets blind pimples', 'targets whiteheads', 'blackhead minimizing','cystic acne relief','hormonal-acne friendly'],
    "aging": ['anti-aging', 'wrinkle reducing'],
    "sensitivity": ['sting-free', 'eye-irritation free', 'sensitive eye friendly', 'irritation-free', 'eye-area friendly','eyelid friendly'],
    "dryness": ['hydrating', 'moisturizer', 'hydrates dry areas', 'flake-free'],
    "oiliness": ['controls eyelid oil', 'controls oil', 'oil-free'],
    "pigmentation": ['dark spot reduction', 'pigmentation reduction', 'discoloration reducing', 'age spot reduction', 'sun spot reduction'],
    "scarring": ['scar healing', 'acne scar reducing'],
    "texture": ['skin smoothing', 'softens skin','promotes supple skin'],
    "uneven skin tone": ['evens tone', 'reduces blotchiness','complexion enhancing'],
    "dark circles": ['diminishes dark circles', 'undereye depuffing','eye bag reduction','boosts eye appearance','beneficial for under-eyes', 'enhances eyelid appearance'],
    "sun protection": ['sunscreen comptabile', 'UV protection', 'soothes sunburn'],
    "eczema": ['eczema soothing'],
    "milia": ['targets milia'],
    "dermatitis": ['dermatitis soothing'],
    "psoriasis": ['helps psoriasis'],
    "inflammation":['depuffing'],
    "rosacea": ['rosacea-friendly','calms redness'],
    "firming": ['firming and tightening','plumping'],
    "dull skin": ['revitalizing for dull skin', 'brightening','promotes dewy skin', 'promotes clear skin','skin brightening'],
    "keratosis pilaris": ['keratosis pilaris-friendly'],
    "skin health": ['skin protection', 'balancing' , 'skin barrier-friendly','promotes healthy skin cells','skin balancing','promotes healthy skin'],
    "pores": ['pore strip', 'refines pores', 'pore cleansing', 'non-clogging', 'decongesting'],
    "detox": ['detoxifying', 'skin detoxifying'],
    "hormonal issues": [],
    "tanning": ['tanning'],
    "lip care": ['lip hydrating', 'lip softening', 'lip plumping', 'lip smoothing', 'for oily lips', 'lip makeup compatible', 'lip product comptabile', 'for dehydrated lips', 'smooths lip wrinkles','lip-friendly','mature lip-friendly'],
    "hand and nail care": ['hand softening', 'enhances hand appearance', 'moisturizes hands'],
    "cleansing": ['cleansing','double cleanse appropriate', 'deep cleansing','removes eye makeup well','removes sunscreen well','removes tan well', 'removes lip makeup well','removes makeup well','gentle cleanse'],
    "makeup-related": ['refreshes makeup', 'makeup compatible', 'compatible with primers', 'compatible with other products', 'makeup alternative', 'enhances makeup longevity', 'makeup-free','great as a base'],
    "packaging": ['quality packaging', 'good size', 'travel-friendly', 'easy dispense','quality applicator'],
    "product attributes": ['eco-friendly', 'vegan', 'cruelty free', 'natural product', 'chemical-free','pregnancy-safe', 'clean product'],
    "eyelash and eyebrow care": ['promotes brow growth ', 'brow lifting', 'darkens eyebrows', 'boosts brow volume', 'promotes eyebrow growth', 'enhances brow health & appearance', 'lash strengthening', 'boosts lash growth', 'enhances lash health & appearance', 'enhances lash curl','eyelash darkening','promotes eyelash growth'],
    "texture/formula": ['smooth texture', 'gel cleanser', 'soft texture', 'gel formula', 'creamy', 'lotion', 'mist formula', 'thick', 'grainy texture', 'liquid formula', 'rich', 'foamy lather', 'gentle', 'pleasant texture', 'heavy', 'spray form', 'clay product', 'serum', 'quality ingredients', 'eye cream', 'tinted moisturizer', 'exfoliating scrub', 'mask','strong formula','breathable','non-sticky','lightweight','toner','balm'],
    "exfoliation": ['gentle exfoliate','effective exfoliator','effective chemical exfoliator'],
    "coverage/finish": ['natural finish', 'sheer coverage', 'good coverage', 'nice finish', 'gloss finish', 'non-glossy', 'matte finish', 'buildable','sheer finish','invisible finish'],
    "application": ['easy to apply', 'absorbs well','no rinse required' , 'easy to blend', 'fast-drying', 'mess-free', 'beginner-friendly','easy to remove','easy to mix'],
    "skin type": ['for normal skin', 'for combination skin', 'suitable for all skin types', 'for dry skin', 'for sensitive skin','for oily skin', 'for dehydrated skin'],
    "skin tone": ['suitable for darker skin tones'],
    "age suitability": ['mature skin-friendly', 'teen-skin friendly', 'suitable for all ages','child-friendly'],
    "skin feeling": ['not tight-feeling', 'soothes irritation','nourishing','pleasant feel', 'cooling', 'tingling sensation','refreshing', 'soothes itchiness', 'rejuvenating', 'drying effect', 'no peeling or flaking','calming','not stripping','skin purging', 'non-drying','pleasant feeling'],
    "fragrance/scent": ['pleasant taste', 'fragrance free', 'pleasant scent'],
    "transferability": ['stain-free', 'transfer-resistant', 'white-cast free', 'cake-free', 'no pilling', 'residue-free', 'streak-free','crease-free'],
    "versatility": ['heat-resistant', 'versatile', 'waterproof', 'long-lasting', 'weatherproof','durable'],
    "color": ['good color accuracy','high color payoff'],
    "usage": ['night use','good for long-term use','overnight use', 'summer suitable','small amount of product required', 'suitable for winter use', 'suitable for daily use', 'seasonal use-friendly', 'suitable for morning use','suitable for long-term use'],
    "promoted": ['promoted reviews'],
    "other skin areas": ['chin-area friendly','jaw-area friendly','neck-friendly','chest-area friendly','T-zone targeted'],
    "price and quality": ['good price','high quality'],
    "general effectiveness": ['effectiveness','effective highlighting','rapid results'],
    "unclassified": ['long battery life', 'red light therapy', 'alternatives']
}

skin_types_dictionary = {
    "combination": ["combination", "combo", "mixed skin", "combination skin", "oily and dry", "combo skin"],
    "dry": ["dry", "dryness", "flaky", "dry skin", "dehydrated", "lacking moisture", "tight skin"],
    "oily": ["oily", "greasy", "oily skin", "shiny skin", "excess oil", "oil-prone", "oiliness"],
    "normal": ["normal", "balanced", "normal skin", "neither dry nor oily", "even skin"],
    "dehydrated": ["dehydrated", "lacking water", "dehydrated skin", "moisture loss", "hydration needed"],
    "acne prone": ["acne prone", "acne-prone skin", "pimples", "breakouts", "blemish prone", "zit prone"],
    "sensitive": ["sensitive", "reactive", "sensitive skin", "easily irritated", "redness prone", "sensitivity"]
}

general_dictionary = {
    "problems": ["acne", "aging", "sensitivity", "dryness", "oiliness", "pigmentation", "scarring", "texture", "uneven skin tone", "dark circles", "sun protection", "eczema", "milia", "dermatitis", "psoriasis", "inflammation", "rosacea", "keratosis pilaris","firming", "dull skin", "pores", "detox", "hormonal issues", "tanning","cleansing", "exfoliation", "coverage/finish"],
    "user parameters": ["skin type", "skin tone", "age suitability"],
    "product parameters":["lip care", "hand and nail care",  "makeup-related", "packaging", "product attributes", "eyelash and eyebrow care", "texture/formula", "application", "skin feeling", "fragrance/scent", "transferability", "versatility", "color", "usage", "promoted", "price and quality", "general effectiveness","other skin areas"]
}